In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn import svm
from sklearn.semi_supervised import label_propagation
from sklearn.semi_supervised import LabelSpreading
import pandas as pd

rng = np.random.RandomState(0)

In [2]:
metro_data = pd.read_csv('metro_summary_data.csv')
sorted_metro_data = metro_data.sort_values('PercentTech', ascending=False)

In [3]:
sorted_metro_data

Unnamed: 0                                          CBSA  TotalPeople  \
204         205            San Jose-Sunnyvale-Santa Clara, CA      1916862   
131         132                                   Madison, WI       523793   
26           27                               Bloomington, IL       173828   
17           18                         Austin-Round Rock, TX      1881313   
185         186                                   Raleigh, NC      1209514   
203         204             San Francisco-Oakland-Hayward, CA      4656199   
211         212                   Seattle-Tacoma-Bellevue, WA      3735393   
230         231                                   Trenton, NJ       370588   
239         240  Washington-Arlington-Alexandria, DC-VA-MD-WV      3780523   
36           37                              Cedar Rapids, IA       220052   
141         142       Minneapolis-St. Paul-Bloomington, MN-WI      2903798   
182         183                                Provo-Orem, UT       575320   
97           98                                    Ithaca, NY       105554   
226         227                               Tallahassee, FL       286605   
45           46                                  Columbia, MO       175096   
67           68                                  Fargo, ND-MN       172249   
71           72                              Fort Collins, CO       333813   
19           20                 Baltimore-Columbia-Towson, MD      2748731   
223         224                             State College, PA       160978   
7             8                                 Ann Arbor, MI       358039   
44           45                     College Station-Bryan, TX       215141   
58           59                        Durham-Chapel Hill, NC       443333   
37           38                          Champaign-Urbana, IL       208363   
189         190                                  Richmond, VA       880431   
106         107                            Kansas City, MO-KS      1431690   
38           39             Charlotte-Concord-Gastonia, NC-SC      1637488   
165         166                   Omaha-Council Bluffs, NE-IA       726026   
192         193                                 Rochester, NY       750191   
49           50               Dallas-Fort Worth-Arlington, TX      6793024   
46           47                                  Columbus, OH      1765795   
..          ...                                           ...          ...   
130         131                                    Madera, CA       154139   
91           92                         Homosassa Springs, FL       141208   
160         161                                    Odessa, TX       159611   
213         214                                 Sheboygan, WI       115119   
146         147                                    Muncie, IN       116910   
133         134                  McAllen-Edinburg-Mission, TX       842623   
111         112                                 Lafayette, LA       240162   
249         250             Youngstown-Warren-Boardman, OH-PA       113929   
145         146                                    Monroe, MI       149419   
22           23                      Beaumont-Port Arthur, TX       255009   
138         139                    Michigan City-La Porte, IN       110774   
162         163                        Ogdensburg-Massena, NY       111302   
77           78                                 Goldsboro, NC       123951   
179         180                                Pottsville, PA       144857   
100         101                Jamestown-Dunkirk-Fredonia, NY       130930   
143         144                                   Modesto, CA       538021   
129         130                         Macon-Bibb County, GA       154207   
85           86                          Hanford-Corcoran, CA       151088   
247         248                                    Yakima, WA       249103   
11           12            

In [4]:
sorted_metro_data['LogMedianRent'] = np.log(sorted_metro_data['MedianRent'])
sorted_metro_data['LogMedianHouseValue'] = np.log(sorted_metro_data['MedianHouseValue'])
sorted_metro_data['LogTotalPeople'] = np.log(sorted_metro_data['TotalPeople'])

In [5]:
array2 = sorted_metro_data.as_matrix(['PercentCollege', 'PercentFemale'])

test_labels = [-1, -1, -1, 1, 1, 1, 1, 1, 1]
rng.shuffle(test_labels)

end_labels = [-1] * (array2.shape[0] - 15) + [0] * 6
rng.shuffle(end_labels)


labels2 = np.asarray(test_labels + end_labels)

prop2 = label_propagation.LabelPropagation(kernel='knn', n_neighbors=7, max_iter=100, alpha=1).fit(array2, labels2)
model_results = prop2.predict(array2)
#np.where(np.asarray(prop2[1]) > 0)
model_results

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
indices = np.where(np.asarray(model_results) > 0)
sorted_metro_data.iloc[indices]['CBSA']

Series([], Name: CBSA, dtype: object)

In [7]:
sorted_metro_data.head()

Unnamed: 0                                CBSA  TotalPeople  TotalTech  \
204         205  San Jose-Sunnyvale-Santa Clara, CA      1916862     114373   
131         132                         Madison, WI       523793      20891   
26           27                     Bloomington, IL       173828       6648   
17           18               Austin-Round Rock, TX      1881313      68831   
185         186                         Raleigh, NC      1209514      42795   

     MedianAge  PercentHighSchool  PercentCollege  PercentPostGrad  \
204       37.0           0.677346        0.353995         0.160663   
131       35.0           0.757956        0.369048         0.129826   
26        33.0           0.747929        0.292554         0.098655   
17        34.0           0.684594        0.302374         0.101011   
185       36.0           0.678530        0.312101         0.109033   

     MedianIncome  PercentFemale  PercentBornOutOfState  PercentImmigrant  \
204       30000.0       0.496868               0.546244          0.400493   
131       30000.0       0.502044               0.409666          0.104973   
26        25000.0       0.511373               0.257571          0.059944   
17        27200.0       0.499367               0.466017          0.170215   
185       27000.0       0.511799               0.533912          0.136046   

     Percent18to35  PercentTech  MedianRent  MedianHouseValue  DiversityIndex  \
204       0.255370     5.966679      1800.0          800000.0        0.701149   
131       0.299702     3.988408       850.0          230000.0        0.344415   
26        0.325857     3.824470       700.0          165000.0        0.347239   
17        0.293115     3.658668       950.0          240000.0        0.609035   
185       0.249252     3.538198       830.0          225000.0        0.565302   

     LogMedianRent  LogMedianHouseValue  LogTotalPeople  
204       7.495542            13.592367       14.466200  
131       6.745236            12.345835       13.168852  
26        6.551080            12.013701       12.065822  
17        6.856462            12.388394       14.447480  
185       6.721426            12.323856       14.005729

In [8]:
sorted_metro_data.index



Int64Index([204, 131,  26,  17, 185, 203, 211, 230, 239,  36,
            ...
            168, 250,  50, 115,  60, 136,  32, 125,  62, 132],
           dtype='int64', length=251)

In [9]:
from sklearn import preprocessing

subset = sorted_metro_data[['PercentCollege',
                  'Percent18to35', 'LogMedianRent', 'DiversityIndex']]
nsmd = pd.DataFrame(
    index = subset.index,
    data = preprocessing.normalize(subset, axis=0),
    columns = subset.columns
)

plt.hist(nsmd.LogMedianRent)


(array([  4.,  28.,  48.,  68.,  50.,  26.,  10.,  10.,   6.,   1.]),
 array([ 0.05748738,  0.05893052,  0.06037367,  0.06181681,  0.06325995,
         0.0647031 ,  0.06614624,  0.06758939,  0.06903253,  0.07047567,
         0.07191882]),
 <a list of 10 Patch objects>)

In [ ]:
plt.hist(sorted_metro_data.MedianRent)


(array([ 30.,  77.,  79.,  37.,   8.,  10.,   3.,   6.,   0.,   1.]),
 array([  400.,   540.,   680.,   820.,   960.,  1100.,  1240.,  1380.,
         1520.,  1660.,  1800.]),
 <a list of 10 Patch objects>)

In [ ]:
bootstrap_model_results = []
for i in range(0, 1000):
    array2 = nsmd.as_matrix(['PercentCollege', 'Percent18to35'])
    #array2 = nsmd
    
    test_labels = [-1, -1, -1, 1, 1, 1, 1, 1, 1]
    rng.shuffle(test_labels)

    end_labels = [-1] * (array2.shape[0] - 15) + [0] * 6
    rng.shuffle(end_labels)


    labels2 = np.asarray(test_labels + end_labels)

    prop2 = label_propagation.LabelPropagation(kernel='knn', n_neighbors=7, max_iter=100, alpha=1).fit(array2, labels2)
    model_results = prop2.predict(array2)
    #np.where(np.asarray(prop2[1]) > 0)
    bootstrap_model_results.append(model_results)

probabilities = np.array([0 for x in range(0, len(bootstrap_model_results[1]))])
for vec in bootstrap_model_results:
    probabilities = np.add(vec / 1000, probabilities)
probabilities
    

In [ ]:
plt.hist(probabilities, bins=25)

In [ ]:
from matplotlib import pyplot as plt
from matplotlib.collections import LineCollection

from sklearn import manifold
from sklearn.metrics import euclidean_distances
from sklearn.decomposition import PCA

#similarities2 = euclidean_distances(nsmd)
similarities2 = euclidean_distances(array2)

seed = np.random.RandomState(seed=3)
mds = manifold.MDS(n_components=2, max_iter=3000, eps=1e-9, random_state=seed,
                   dissimilarity="precomputed", n_jobs=1)
pos = mds.fit(similarities2).embedding_
nmds = manifold.MDS(n_components=2, metric=False, max_iter=3000, eps=1e-12,
                    dissimilarity="precomputed", random_state=seed, n_jobs=1,
                    n_init=1)
npos = nmds.fit_transform(similarities2, init=pos)

In [ ]:
%matplotlib inline
# Rescale the data
pos *= np.sqrt((array2 ** 2).sum()) / np.sqrt((pos ** 2).sum())
npos *= np.sqrt((array2 ** 2).sum()) / np.sqrt((npos ** 2).sum())

# Rotate the data
clf = PCA(n_components=2)
array2 = clf.fit_transform(array2)

pos = clf.fit_transform(pos)

npos = clf.fit_transform(npos)

fig = plt.figure(1)
ax = plt.axes([0., 0., 1., 1.])

s = 50
plt.scatter(npos[np.where(np.asarray(probabilities) >= .5), 0], npos[np.where(np.asarray(probabilities) >= .5), 1], color='blue', s=s, lw=0, label='Good for tech')
plt.scatter(npos[np.where(np.asarray(probabilities) < .5), 0], npos[np.where(np.asarray(probabilities) < .5), 1], color='darkorange', s=s, lw=0, label='Less good for tech')

plt.legend(scatterpoints=1, loc='best', shadow=False)

In [ ]:
indices = np.where(np.asarray(probabilities) >= 0.5)
#sorted_metro_data.iloc[indices]['CBSA']

indices

In [ ]:
indices = np.where(np.asarray(probabilities) >= 0.5)
good_for_tech = sorted_metro_data.iloc[indices]

In [ ]:
similarity_matrix = euclidean_distances(nsmd)

sorted_metro_data['GoodForTech'] = np.where(np.asarray(probabilities) >= 0.5, 'Yes', 'No')

In [ ]:
sorted_metro_data

In [ ]:
import pymysql.cursors

user = 'kkutchko'
passwd = 'password'
database = 'metro_areas'

connection = pymysql.connect(host='localhost',
    user=user,
    password=passwd,
    db=database,
    cursorclass=pymysql.cursors.DictCursor)

drop_table_cmd = "drop table if exists metro_data"
drop_table_cmd2 = "drop table if exists city_distance"

create_table_cmd = "create table if not exists metro_data (" +\
    "CBSA varchar(64), " +\
    "TotalPeople int(8), " +\
    "PercentCollege decimal(7, 4), " +\
    "Percent18to35 decimal(7, 4), " +\
    "MedianRent int(5), " +\
    "DiversityIndex decimal(5, 4), " +\
    "GoodForTech varchar(5), " +\
    "primary key (CBSA))"
    
create_table_cmd2 = "create table if not exists city_distance (" +\
    "CBSA1 varchar(64), " +\
    "CBSA2 varchar(64), " +\
    "distance decimal(11, 8), " +\
    "primary key (CBSA1, CBSA2))"

insert_cmd = "insert into metro_data " +\
    "(CBSA, TotalPeople, PercentCollege, Percent18to35, MedianRent, DiversityIndex, GoodForTech) " +\
    'values ("%s", %s, %s, %s, %s, %s, "%s") ' +\
    "on duplicate key update CBSA = CBSA"
    
insert_cmd2 = "insert into city_distance " +\
    "(CBSA1, CBSA2, distance) " +\
    'values ("%s", "%s", %s) ' +\
    'on duplicate key update CBSA1=CBSA1, CBSA2=CBSA2'
    
try:
    with connection.cursor() as cursor:
        # create table with city data
        cursor.execute(drop_table_cmd)
        cursor.execute(create_table_cmd)

        for idx, line in sorted_metro_data.iterrows():
            cursor.execute(insert_cmd, (line['CBSA'], line['TotalPeople'],
                line['PercentCollege'] * 100, line['Percent18to35'] * 100,
                line['MedianRent'], line['DiversityIndex'],
                line['GoodForTech']))
            
        # create table for euclidean distances
        cursor.execute(drop_table_cmd2)
        cursor.execute(create_table_cmd2)
        
        for x in range(0, len(similarity_matrix)):
            for y in range(0, len(similarity_matrix[x])):
                matrix_data = (sorted_metro_data['CBSA'].iloc[x],
                     sorted_metro_data['CBSA'].iloc[y],
                     float(similarity_matrix[x][y]))
                if matrix_data[0] != matrix_data[1]:
                    cursor.execute(insert_cmd2, matrix_data)
        
finally:
    connection.commit()
    connection.close()
    



In [ ]:
plt.imshow(similarity_matrix)